name: CI
on:
  pull_request:
    branches:
      - default
  push:
    branches:
      - default
  release:
    types: [published]
jobs:
  build:
    name: Build / ${{ matrix.os }} / Python ${{ matrix.major }}.${{ matrix.minor }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        major: [3]
        minor: [10]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
      - uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_BEFORE_BUILD: pip install -r {project}/requirements-test.txt
          CIBW_BUILD: cp${{ matrix.major }}${{ matrix.minor }}-*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_TEST: pip install -r {project}/requirements-test.txt
          CIBW_TEST_COMMAND: pytest {project}/test
